# cnb sever
  # checkout
  # artifact upload: docker login, build & push

# turn tencent server to runner

# docker registry, staytuned

# tencent server
  # checkout
  # artifact download: docker login, docker pull
  # deploy: docker compose up -d --build

main:
  push:
    - services:
        - docker
      imports:
        - https://cnb.cool/dao77777.cloud/secrets/-/blob/main/env.yml
      stages:
        # Build & push agents
        - name: docker build
          script: docker build -t ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}/agents:latest ./agents
        - name: docker push
          script: docker push ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}/agents:latest
        # Build & push yyyyy
        - name: docker build
          script: docker build -t ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}/yyyyy:latest ./yyyyy
        - name: docker push
          script: docker push ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}/yyyyy:latest
        # Deploy by ssh connecting to my tencent server
        - name: deploy
          image: tencentcom/ssh
          settings:
            host: ${TENCENT_SERVER_HOST}
            username: ${TENCENT_SERVER_USER}
            password: ${TENCENT_SERVER_PASSWORD}
            port: 22
            script:
              - cd ~/cooper
              - export DOCKER_REGISTRY=${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}
              - export BYTE_DANCE_AI_MODEL_API_KEY=${BYTE_DANCE_AI_MODEL_API_KEY}
              - git pull
              - docker compose pull
              - docker compose up --build -d