main:
  push:
    - services:
        - docker
      imports:
        - https://cnb.cool/dao77777.cloud/secrets/-/blob/main/.env
      stages:
        # Build & push agents
        - name: docker build
          script: docker build -t ${CNB_DOCKER_REGISTRY}/${CNB_COOPER_REPOSITORY_SLUG}/agents:latest ./agents
        - name: docker push
          script: docker push ${CNB_DOCKER_REGISTRY}/${CNB_COOPER_REPOSITORY_SLUG}/agents:latest
        # Build & push yyyyy
        - name: docker build
          script: docker build -t ${CNB_DOCKER_REGISTRY}/${CNB_COOPER_REPOSITORY_SLUG}/yyyyy:latest ./yyyyy
        - name: docker push
          script: docker push ${CNB_DOCKER_REGISTRY}/${CNB_COOPER_REPOSITORY_SLUG}/yyyyy:latest
        # Deploy by ssh connecting to my tencent server
        - name: deploy
          image: tencentcom/ssh
          settings:
            host: ${VIRTUAL_MACHINE_DOMAIN}
            username: ${VIRTUAL_MACHINE_DEPLOY_USERNAME}
            password: ${VIRTUAL_MACHINE_DEPLOY_PASSWORD}
            port: 22
            script:
              - cd ~/cooper
              - cat ~/.env
              # - echo ${CNB_REPO_SLUG_LOWERCASE}
              # - export CNB_DOCKER_REGISTRY=${CNB_DOCKER_REGISTRY}
              # - export CNB_REPO_SLUG_LOWERCASE=${CNB_REPO_SLUG_LOWERCASE}
              # - export BYTE_DANCE_AI_MODEL_API_KEY=${BYTE_DANCE_AI_MODEL_API_KEY}
              # - export POSTGRES_CONNECTION=${POSTGRES_CONNECTION}
              # - export YYYYY_PORT=${YYYYY_PORT}
              - git pull
              - docker compose pull
              - docker compose up --build -d --env-file ~/.env