import type { Metadata } from "next";
import "./globals.css";
import { UI } from "./_ui";
import { ThemeProvider } from "./_lib/theme/_provider";
import { ReactQueryProvider } from "./_lib/react-query/_provider";

export const metadata: Metadata = {
  title: "xxxxx",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <ReactQueryProvider>
          <ThemeProvider>
            <UI>
              {children}
            </UI>
          </ThemeProvider>
        </ReactQueryProvider>
      </body>
    </html>
  )
}
