import type { Metadata } from "next";
import "./globals.css";
import { ReactQueryProvider } from "./_lib/react-query/_provider";
import { ThemeProvider } from "./_lib/theme/_provider";

export const metadata: Metadata = {
  title: "xxxxx",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <ReactQueryProvider>
          <ThemeProvider>
            {children}
          </ThemeProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
