name: Cooper Deployment

env:
  DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_NAMESPACE: ${{ secrets.DOCKER_NAMESPACE }}

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Log in to Docker registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Agents Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./agents
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_NAMESPACE }}/agents:latest
      - name: Build and push Yyyyy Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./yyyyy
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_NAMESPACE }}/yyyyy:latest
  deploy:
    runs-on: self-hosted
    needs: build-and-push
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Log in to Docker registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Deploy with Docker Compose
        run: |
          docker compose pull
          docker compose up --build -d
      - name: List containers
        run: docker ps
