name: Cooper Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Deploy with Docker Compose
        run: |
          docker compose down
          docker compose up --build -d
      - name: List containers
        run: docker ps
