name: Sync to CNB
on: [push]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Sync to CNB Repository
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:${{ github.workspace }} \
            -w ${{ github.workspace }} \
            -e PLUGIN_TARGET_URL=${{ secrets.CNB_REPOSITORY }} \
            -e PLUGIN_AUTH_TYPE="https" \
            -e PLUGIN_USERNAME=${{ secrets.CNB_ORG_GIT_PASSWORD }} \
            -e PLUGIN_PASSWORD=${{ secrets.CNB_ORG_GIT_PASSWORD }} \
            -e PLUGIN_FORCE="true" \
            tencentcom/git-sync